// form-data.jsx

import { pl } from "date-fns/locale";
import { title } from "process";

export const employeeData = [
  {
    employeerId: "5LD01234",
    fullName: "สมชาย ใจดี",
    department: "ITH-CV", // ITH-CV
    group: "CV1", // CV1
  },
];

// List of departments
export const list_department = [
  { id: 1, name: "ITH-CV", group: "ITH" },
  { id: 2, name: "ITH-MO", group: "ITH" },
  { id: 3, name: "ITH-MT", group: "ITH" },
  { id: 4, name: "ITH-AUX", group: "ITH" },
  { id: 5, name: "ITH-OE", group: "ITH" },
  { id: 6, name: "VCS-Sub", group: "SUB" },
  { id: 7, name: "STN-Sub", group: "SUB" },
  { id: 8, name: "SDS-Sub", group: "SUB" },
  { id: 9, name: "3SL-Sub", group: "SUB" },
];

// List of groups per department
export const list_group = [
  { id: 1, name: "CV1", depart: "ITH-CV" },
  { id: 2, name: "CV2", depart: "ITH-CV" },
  { id: 3, name: "CV3", depart: "ITH-CV" },
  { id: 4, name: "CV4", depart: "ITH-CV" },
  { id: 5, name: "CV5", depart: "ITH-CV" },
  { id: 6, name: "CV6", depart: "ITH-CV" },
  { id: 7, name: "CV7", depart: "ITH-CV" },
  { id: 8, name: "CV8", depart: "ITH-CV" },
  { id: 9, name: "CV9", depart: "ITH-CV" },
  { id: 10, name: "CV10", depart: "ITH-CV" },
  { id: 11, name: "CV11", depart: "ITH-CV" },
  { id: 12, name: "CV12", depart: "ITH-CV" },
  { id: 13, name: "CV13", depart: "ITH-CV" },
  { id: 14, name: "CV14", depart: "ITH-CV" },
  { id: 15, name: "CV15", depart: "ITH-CV" },
  { id: 16, name: "CV16", depart: "ITH-CV" },
  { id: 17, name: "MO1", depart: "ITH-MO" },
  { id: 18, name: "MO2", depart: "ITH-MO" },
  { id: 19, name: "MO3", depart: "ITH-MO" },
  { id: 20, name: "MO4", depart: "ITH-MO" },
  { id: 21, name: "MO5", depart: "ITH-MO" },
  { id: 22, name: "MO6", depart: "ITH-MO" },
  { id: 23, name: "MO7", depart: "ITH-MO" },
  { id: 24, name: "MO8", depart: "ITH-MO" },
  { id: 25, name: "MT1", depart: "ITH-MT" },
  { id: 26, name: "MT2", depart: "ITH-MT" },
  { id: 27, name: "MT3", depart: "ITH-MT" },
  { id: 28, name: "MT4", depart: "ITH-MT" },
  { id: 29, name: "MT5", depart: "ITH-MT" },
  { id: 30, name: "AUX1", depart: "ITH-AUX" },
  { id: 31, name: "AUX2", depart: "ITH-AUX" },
  { id: 32, name: "AUX3", depart: "ITH-AUX" },
  { id: 33, name: "AUX4", depart: "ITH-AUX" },
  { id: 34, name: "AUX5", depart: "ITH-AUX" },
  { id: 35, name: "AUX6", depart: "ITH-AUX" },
  { id: 36, name: "AUX7", depart: "ITH-AUX" },
  { id: 37, name: "AUX8", depart: "ITH-AUX" },
  { id: 38, name: "SV1", depart: "ITH-OE" },
  { id: 39, name: "SV2", depart: "ITH-OE" },
  { id: 40, name: "SHE", depart: "ITH-OE" },
  { id: 41, name: "COST", depart: "ITH-OE" },
  { id: 42, name: "COM", depart: "ITH-OE" },
  { id: 43, name: "SARALY", depart: "ITH-OE" },
  { id: 44, name: "PDC", depart: "ITH-OE" },
  { id: 45, name: "ISO", depart: "ITH-OE" },
  { id: 46, name: "AM/HR", depart: "ITH-OE" },
  { id: 47, name: "TM", depart: "ITH-OE" },
  { id: 48, name: "STORE", depart: "ITH-OE" },
  { id: 49, name: "PSL", depart: "ITH-OE" },
];

// Safety category data
export const safetyCategoryData = [
  {
    id: 1,
    name: "การสวมใส่อุปกรณ์คุ้มครองส่วนบุคคล PPE",
    imagePath: "/img/ppe.png",
    alt: "PPE",
  },
  {
    id: 2,
    name: "การใช้อุปกรณ์ เครื่องมือ เครื่องจักร และยานพาหนะต่างๆ ในการทำงาน Tool / Equipment / Machine / Vehicle",
    imagePath: "/img/tools.png",
    alt: "Tools",
  },
  {
    id: 3,
    name: "การกระทำที่ไม่ปลอดภัย และการจับชิ้นส่วน Unsafe Action / Driving / Line of fire",
    imagePath: "/img/unsafe.png",
    alt: "Unsafe Action",
  },
  {
    id: 4,
    name: "สภาพแวดล้อมที่ไม่ปลอดภัย Plant / Unsafe Condition (UC)",
    imagePath: "/img/condition.png",
    alt: "Unsafe Condition",
  },
];

// Sub-safety category data
export const sub_safetyCategoryData = [
  {
    id: 1,
    form_safety_id: 1,
    name: "PPE งานซ่อมบำรุง และงานก่อสร้าง (Maintenance / Construction)",
    imagePath: "/img/maintenance.png",
    alt: "รูป PPE (ME)",
    type: "multiselect",
    subject: "งานที่สังเกตุ",
    placeholder: "ระบุงานที่สังเกตุ",
    title:"ประเภทอุปกรณ์ PPE ที่สังเกตุ",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MT" },
      { id: 3, name: "AUX" },
      { id: 4, name: "SUB-VCS" },
      { id: 5, name: "SUB-STN" },
      { id: 6, name: "SUB-SDS" },
      { id: 7, name: "SUB-3SL" },
    ],
    option: [
      { id: 1, name: "หมวกเซฟตี้" },
      { id: 2, name: "รองเท้าเซฟตี้" },
      { id: 3, name: "เสื้อสะท้อนแสง" },
      { id: 4, name: "อุปกรณ์ป้องกันดวงตา" },
      { id: 5, name: "อุปกรณ์ป้องกันการตก" },
      { id: 6, name: "อุปกรณ์ป้องกันระบบทางเดินหายใจ" },
      { id: 7, name: "อุปกรณ์ป้องกันมือหรือผิวหนัง" },
    ],
  },
  {
    id: 2,
    form_safety_id: 1,
    name: "PPE งานไฟฟ้า (Electrical)",
    imagePath: "/img/electrical.png",
    alt: "รูป PPE (EE)",
    type: "multiselect",
    subject: "งานที่สังเกตุ",
    placeholder: "ระบุงานที่สังเกตุ",
    title:"ประเภทอุปกรณ์ PPE ที่สังเกตุ",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MT" },
      { id: 3, name: "AUX" },
    ],
    option: [
      { id: 1, name: "หมวกเซฟตี้" },
      { id: 2, name: "รองเท้าเซฟตี้" },
      { id: 3, name: "เสื้อสะท้อนแสง" },
      { id: 4, name: "อุปกรณ์ป้องกันดวงตา" },
      { id: 5, name: "อุปกรณ์ป้องกันการตก" },
      { id: 6, name: "อุปกรณ์ป้องกันระบบทางเดินหายใจ" },
      { id: 7, name: "อุปกรณ์ป้องกันมือหรือผิวหนัง" },
      { id: 8, name: "อุปกรณ์ป้องกันไฟฟ้า" },
    ],
  },
  {
    id: 3,
    form_safety_id: 1,
    name: "PPE งานทั่วไปและอื่นๆ (Basic)",
    imagePath: "/img/ppe basic.png",
    alt: "รูป PPE (EE)",
    type: "multiselect",
    subject: "งานที่สังเกตุ",
    placeholder: "ระบุงานที่สังเกตุ",
    title:"ประเภทอุปกรณ์ PPE ที่สังเกตุ",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MT" },
      { id: 3, name: "AUX" },
      { id: 4, name: "SUB-VCS" },
      { id: 5, name: "SUB-STN" },
      { id: 6, name: "SUB-SDS" },
      { id: 7, name: "SUB-3SL" },
      { id: 8, name: "OE" },
      { id: 9, name: "MO" },
    ],
    option: [
      { id: 1, name: "หมวกเซฟตี้" },
      { id: 2, name: "รองเท้าเซฟตี้" },
      { id: 3, name: "เสื้อสะท้อนแสง" },
      { id: 4, name: "อุปกรณ์ป้องกันดวงตา" },
      { id: 5, name: "อุปกรณ์ป้องกันระบบทางเดินหายใจ" },
    ],
  },
  {
    id: 4,
    form_safety_id: 2,
    name: "อุปกรณ์ เครื่องมือ Tool/ Equipment และงานก่อสร้าง งานซ่อมบำรุง (Maintenance / Construction)",
    imagePath: "/img/maintenance.png",
    alt: "รูป Maintenance (Tool/Equipment)",
    type: "multiselect",
    subject: "งานที่สังเกตุ",
    placeholder: "ระบุงานที่สังเกตุ",
    title:"สังเกตุ การใช้อุปกรณ์ เครื่องมือต่างๆในการทำงาน Tools/ Machine/ Equipment",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MT" },
      { id: 3, name: "AUX" },
      { id: 4, name: "SUB-VCS" },
      { id: 5, name: "SUB-STN" },
      { id: 6, name: "SUB-SDS" },
      { id: 7, name: "SUB-3SL" },
      { id: 8, name: "MO" },
    ],
    option: [
      {
        id: 1,
        name: "อุปกรณ์การยก (ลวดสลิง สลิงผ้าใบ ตะขอ สะเก็น คลิปล๊อค ฯลฯ)",
      },
      {
        id: 2,
        name: "เครื่องมือ อุปกรณ์งานซ่อมบำรุง (Cover guard เครื่องเจียร์ เครื่องตัดไฟเบอร์ สว่าน)",
      },
      {
        id: 3,
        name: "อุปกรณ์สำหรับงานเชื่อม ( กันไฟย้อน สภาพสายไฟ สภาพสายลมสายแก็ส สายเชื่อมด้ามจับเชื่อม)",
      },
      { id: 4, name: "สภาพสายไฟ สายกราวน์ของเครื่องมือ หรืออุปกรณ์ต่างๆ" },
    ],
  },
  {
    id: 5,
    form_safety_id: 2,
    name: "อุปกรณ์ เครื่องมือ Tool/ Equipment งานไฟฟ้า (Electrical)",
    imagePath: "/img/electrical.png",
    alt: "รูป Electrical (Tool/Equipment)",
    type: "multiselect",
    subject: "งานที่สังเกตุ",
    placeholder: "ระบุงานที่สังเกตุ",
    title:"สังเกตุ การใช้อุปกรณ์ เครื่องมือต่างๆในการทำงาน Tools/ Machine/ Equipment",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MO" },
      { id: 3, name: "MT" },
      { id: 4, name: "AUX" },
    ],
    option: [
      { id: 1, name: "แขวน Tag-out / Log-out" },
      {
        id: 2,
        name: "สภาพความพร้อมของอุปกรณ์เครื่องมืองานไฟฟ้า เช่นไม้ชักฟิว ฯลฯ",
      },
      { id: 3, name: "สภาพตู้ไฟและระบบตัดไฟอัตโนมัติ" },
      { id: 4, name: "สภาพสายไฟ สายกราวน์ของเครื่องมือ หรืออุปกรณ์ต่างๆ" },
      { id: 5, name: "การติด Tag ระบุหมายเลขหรือชี้บ่งสถานะ" },
    ],
  },
  {
    id: 6,
    form_safety_id: 2,
    name: "อุปกรณ์ ต่างๆของยานพาหนะและเครื่องจักร",
    imagePath: "/img/truck.png",
    alt: "รูป ยานพาหนะเครื่องจักรที่สังเกตุ",
    type: "multiselect",
    subject: "ประเภทเครื่องจักรที่สังเกตุ / หมายเลขเครื่องจักร",
    placeholder: "เช่น รถยนต์ SHE13 / รถเครน ITH1 / รถบรรทุก STN25 / รถเฮี้ยบ MT01 ",
    title:"สังเกตุ  อุปกรณ์ ต่างๆของยานพาหนะและเครื่องจักร",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MO" },
      { id: 3, name: "MT" },
      { id: 4, name: "AUX" },
      { id: 5, name: "OE" },
      { id: 6, name: "SUB-VCS" },
      { id: 7, name: "SUB-STN" },
      { id: 8, name: "SUB-SDS" },
      { id: 9, name: "SUB-3SL" },
    ],
    option: [
      {
        id: 1,
        name: "สภาพเครื่องจักรโดยรอบ เช่น ตัวโครงสร้าง กระจก ลมยาง ฯลฯ",
      },
      { id: 2, name: "ระบบไฟส่องสว่าง" },
      { id: 3, name: "ธงสะท้อนแสง" },
      { id: 4, name: "ไฟไซเรน" },
      { id: 5, name: "สติกเกอร์สะท้อนแสง และหมายเลข" },
      { id: 6, name: "ถังดับเพลิง / Spill kits" },
      { id: 7, name: "ยางกันกระแทก" },
    ],
  },
  {
    id: 7,
    form_safety_id: 3,
    name: "พฤติกรรมการทำงานซ่อมบำรุง และงานก่อสร้าง(Maintenance / Construction)",
    imagePath: "/img/maintenance.png",
    alt: "รูป พฤติกรรมที่สังเกตุ",
    type: "multiselect",
    subject: "งานที่สังเกตุ",
    placeholder: "ระบุงานที่สังเกตุ",
    title:"การทำงานบน Line of fire หรือ การกระทำที่ไม่ปลอดภัย Unsafe Action (งานซ่อมบำรุงและงานก่อสร้าง)",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MO" },
      { id: 3, name: "MT" },
      { id: 4, name: "AUX" },
      { id: 5, name: "OE" },
      { id: 6, name: "SUB-VCS" },
      { id: 7, name: "SUB-STN" },
      { id: 8, name: "SUB-SDS" },
      { id: 9, name: "SUB-3SL" },
    ],
    option: [
      { id: 1, name: "ทำงานอยู่ใต้พื้นที่เสี่ยงที่อาจมีของตกหล่นทับ" },
      { id: 2, name: "ทำงานอยู่ในพื้นที่แคบที่อาจถูกหนีบ บีบอัดหรือกักขัง" },
      {
        id: 3,
        name: "ทำงานอยู่ในตำแหน่งหรือระยะที่เสี่ยงต่อการถูกสะเก็ดหรือสิ่งของวัถตุกระเด็น",
      },
      {
        id: 4,
        name: "ถอดประกอบอุปกรณ์หรือวัตถุโดยไม่มีสิ่งคำ้ยัน พะยุงหรือรองรับ",
      },
      {
        id: 5,
        name: "ยืนอยู่บนขอบหรืออยู่ในตำแหน่งที่เสี่ยงต่อการตกจากที่สูง",
      },
      { id: 6, name: "ทำงานเร่งรีบ ลัดขั้นตอน" },
      { id: 7, name: "หยอกล้อกันในการทำงานที่มีความเสี่ยง" },
      { id: 8, name: "เล่นมือถือขณะทำงานหรือสูบบุหรี่ในพื้นที่อันตราย" },
      { id: 9, name: "การตัดจ่ายพลังงานขณะทำงาน" },
      { id: 10, name: "ใช้เครื่องมือผิดประเภท หรือเครื่องมือที่ชำรุด" },
      {
        id: 11,
        name: "การติดตั้งป้ายเตือนบ่งบอกสถานะอันตราย หรือปิดกันพื้นที่ขณะทำงาน",
      },
    ],
  },
  {
    id: 8,
    form_safety_id: 3,
    name: "พฤติกรรมการทำงานไฟฟ้า (Electrical)",
    imagePath: "/img/electrical.png",
    alt: "รูป Electrical (Tool/Equipment)",
    type: "multiselect",
    subject: "งานที่สังเกตุ",
    placeholder: "ระบุงานที่สังเกตุ",
    title:"การทำงานบน Line of fire หรือ การกระทำที่ไม่ปลอดภัย Unsafe Action (งานไฟฟ้า)",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MO" },
      { id: 3, name: "MT" },
      { id: 4, name: "AUX" },
    ],
    option: [
      { id: 1, name: "ทำงานอยู่ใต้พื้นที่เสี่ยงที่อาจมีของตกหล่นทับ หรือพื้นที่เปียกแฉะ" },
      {
        id: 2,
        name: "ยืนอยู่บนขอบหรืออยู่ในตำแหน่งที่เสี่ยงต่อการตกจากที่สูง",
      },
      { id: 3, name: "ทำงานเร่งรีบ ลัดขั้นตอน" },
      { id: 4, name: "หยอกล้อกันในการทำงานที่มีความเสี่ยง" },
      { id: 5, name: "เล่นมือถือขณะทำงานหรือสูบบุหรี่ในพื้นที่อันตราย" },
      { id: 6, name: "การตัดจ่ายพลังงานหรือกระแสไฟฟ้าขณะทำงาน" },
      { id: 7, name: "ใช้เครื่องมือผิดประเภท หรือเครื่องมือที่ชำรุด" },
      {
        id: 8,
        name: "การติดตั้งป้ายเตือนบ่งบอกสถานะอันตราย หรือปิดกันพื้นที่ขณะทำงาน",
      },
      { id: 9, name: "การสื่อการการตัดจ่ายกระแสไฟ" },
      { id: 10, name: "การตรวจเช็คกระแสไฟฟ้าค้างในสาย Test voltage" },
    ],
  },
  {
    id: 9,
    form_safety_id: 3,
    name: "พฤติกรรมการขับขี่เครื่องจักรและยานพาหนะ",
    imagePath: "/img/cars.png",
    alt: "รูป ยานพาหนะเครื่องจักรที่สังเกตุ",
    type: "multiselect",
    subject: "ประเภทเครื่องจักรที่สังเกตุ / หมายเลขเครื่องจักร",
    placeholder: "เช่น รถยนต์ SHE13 / รถเครน ITH1 / รถบรรทุก STN25 / รถเฮี้ยบ MT01 ",
    title:"สังกัดแผนกที่ถูกสังเกตุ / การขับขี่เครื่องจักรและยานพาหนะ",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MO" },
      { id: 3, name: "MT" },
      { id: 4, name: "AUX" },
      { id: 5, name: "OE" },
      { id: 6, name: "SUB-VCS" },
      { id: 7, name: "SUB-STN" },
      { id: 8, name: "SUB-SDS" },
      { id: 9, name: "SUB-3SL" },
    ],
    option: [
      {
        id: 1,
        name: "SPEED LIMIT / การใช้ความเร็วในการขับที่ทางราบ 30 กม/ชม",
      },
      { id: 2, name: "SPEED LIMIT / การใช้ความเร็วในการขับที่ทางลาดชัน 25 กม/ชม" },
      { id: 3, name: "SAFE DISTANCE / การเว้นระยะห่างในการขับขี่ 35 เมตร" },
      { id: 4, name: "KYT / การหยุดทำ KYT ก่อนเข้าทางร่วมทางแยก" },
      { id: 5, name: "GEAR CHANGE / การเปลี่ยนเกียร์กลางเนิน" },
      { id: 6, name: "OVERTAKE / การแซงในพื้นที่อันตราย" },
      { id: 7, name: "การกระทำอันตราย Line of fire" }
    ],
  },
  {
    id: 10,
    form_safety_id: 4,
    name: "สภาพแวดล้อมที่ไม่ปลอดภัย Plant / Unsafe Condition (UC)",
    imagePath: "/img/condition.png",
    alt: "Plan/Unsafe Condition (UC)",
    type: "option",
    subject: "พื้นที่พบเจอ",
    placeholder: "ระบุพื้นที่พบเจอ",
    title:"ประเภทความเสี่ยง Unsafe condition",
    departcategory: [
      { id: 1, name: "CV" },
      { id: 2, name: "MO" },
      { id: 3, name: "MT" },
      { id: 4, name: "AUX" },
      { id: 5, name: "OE" },
    ],
    option: [
      {
        id: 1,
        name: "1. เครื่องมือ/เครื่องจักรไม่ปลอดภัย (Unsafe Tools/Equipment) เช่น เครื่องมือชำรุด แตกหัก บิ่น /เครื่องจักรไม่มีฝาครอบป้องกัน (Machine Guard) / ไม่มีระบบตัดไฟอัตโนมัติเมื่อฉุกเฉิน",
      },
      {
        id: 2,
        name: "2. ระบบไฟฟ้าไม่ปลอดภัย (Unsafe Electrical Systems) เช่น สายไฟชำรุด เปลือย ไหม้ / ปลั๊ก เต้ารับ หลวม หรือมีคราบเขม่า /  ไม่มีระบบสายดิน (Grounding)",
      },
      {
        id: 3,
        name: "3. การจัดการสารเคมีไม่ปลอดภัย (Unsafe Chemical Handling) เช่น เก็บสารเคมีในภาชนะที่ไม่เหมาะสม / ไม่มีฉลาก/ป้ายเตือนสารเคมี / ไม่มีอุปกรณ์ระบายอากาศ",
      },
      {
        id: 4,
        name: "4. ความเสี่ยงจากไฟและระเบิด (Fire and Explosion Hazards) เช่น วัตถุไวไฟเก็บใกล้แหล่งความร้อน / ไม่มีระบบป้องกันไฟ เช่น ถังดับเพลิงหรือ fire alarm / ใช้เปลวไฟใกล้สารไวไฟ",
      },
      {
        id: 5,
        name: "5. สภาพแวดล้อมทางกายภาพไม่ปลอดภัย (Unsafe Physical Environment) เช่น พื้นลื่น พื้นต่างระดับไม่มีป้ายเตือน  / มีสิ่งกีดขวางทางเดิน / ทางหนีไฟ / แสงสว่างไม่เพียงพอ",
      },
      {
        id: 6,
        name: "6. ระบบระบายอากาศไม่เหมาะสม (Poor Ventilation) เช่น ทำงานในพื้นที่อับอากาศโดยไม่มีการถ่ายเทอากาศ /  กลิ่นสารเคมีรุนแรงสะสมในบริเวณปฏิบัติงาน",
      },
      {
        id: 7,
        name: "7. ขาดอุปกรณ์ความปลอดภัย (Lack of Safety Devices) เช่น ไม่มีถังดับเพลิงหรืออยู่ในสภาพใช้งานไม่ได้ / ไม่มีอุปกรณ์ช่วยชีวิตในพื้นที่เสี่ยง (เช่น ถังออกซิเจน, สายช่วยชีวิต) / ไม่มี PPE หรือ PPE ไม่เหมาะสม",
      },
      { id: 8, name: "8. อื่นๆ" },
    ],
  },
];
